### ISSUE TITLE
try to move phoenix 1.3 can't make elm work

### ISSUE THREAD

**Issue by jiamo** [jeffcole/loops_with_friends#1]
I am not sure here is a good place to ask this question.
I try to move this project to phoenix 1.3, this is what I have done.  https://github.com/jiamo/loops_with_friends

after `mix phx.server`
There is error:
```
(index):29 Uncaught TypeError: Cannot read property 'fullscreen' of undefined
    at HTMLDocument.<anonymous> ((index):29)
```
index.html have some code 
```
<script>
  document.addEventListener("DOMContentLoaded", function (event) {
    var elmApp = Elm.App.fullscreen({
      host: document.location.host,
      topic: "jams:8b19da18-c1a4-41a8-b28d-ae987ac6bb0f"
    });
  });
```
In browser the elm package was downloaded. So I can't figure out.

**Comment by jeffcole** [comment]
Hi @jiamo, thanks for reporting this. I don't have time to upgrade the app to Phoenix 1.3 right now but hope to in the future.

**Comment by jiamo** [comment]
Today, I am not sure I am using the best method to migrate. Now I can listening the loop sound using  Phoenix 1.3. (Still need to understand deeply.)  So I close it at now..
